'use client'
import {Inter} from 'next/font/google'
import './globals.css'
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";

const inter = Inter({subsets: ['latin']})
const queryClient = new QueryClient()

const metadata = {
    title: 'CoinBase',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <QueryClientProvider client={queryClient}>
            <html lang="en" className="!scroll-smooth">
            <head>
                <title>CoinBase</title>
                <link rel="icon" href="/public/bitcoin-32x32.svg" />
            </head>
            <body className={inter.className}>
            {children}</body>
            </html>
        </QueryClientProvider>
    )
}
